name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

      # Sets up .NET Core SDK 7.x
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.x
          include-prerelease: false
       
      # Publishes Blazor project to the release-folder
      - name: Publish .NET Core Project
        run: dotnet publish BlazorAppTest/BlazorAppTest.csproj -c Release -o release --nologo

      # Copy index.html to 404.html to serve the same file when a file is not found
      - name: copy index.html to 404.html
        run: cp release/wwwroot/index.html release/wwwroot/404.html
        
      # Add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll

      - uses: JamesIves/github-pages-deploy-action@4.1.4
        name: gh-pages publish
        with:
          branch: gh-pages
          folder: ./TypeInfoApp/bin/release/net6.0/publish/wwwroot
